django_projects/news_project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("auth_user/", include("auth_user.urls", namespace="auth_user")),
    path("recipe/", include("recipe.urls", namespace="recipe"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_projects/news_project/main/urls.py
from django.urls import path
from .views import index, blog, detail, create, create_form, delete, update

app_name = 'main'


urlpatterns = [
    path("", index, name="index"),
    path("article/", blog, name="blogs"),
    path("article/<slug:slug>", detail, name="detail"),
    path("create/", create, name="create"),
    path("create-form/", create_form, name="create_form"),
    path("article/delete/<int:pk>", delete, name="delete"),
    path("article/update/<int:pk>", update, name="update"),
]

django_projects/news_project/recipe/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, my_recipe, ingredient_create

app_name = "recipe" 


urlpatterns = [
    path("list/", recipe_list, name="list"),
    path("detail/<slug:slug>", recipe_detail, name='detail'),
    path("create-form/", recipe_create, name="recipe_create"),
    path("update/<slug:slug>", recipe_update, name="recipe_update"),
    path("delete/<slug:slug>", recipe_delete, name="recipe_delete"),
    path("my-recipe/", my_recipe, name="my_recipe"),
    path("ingredient-create/<slug:slug>", ingredient_create, name="ingredient_create"),
]

django_projects/news_project/recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='recipe_images/')
    slug = models.SlugField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, default=1)
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
def recipe_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        base_slug = slugify(instance.title)
        slug = base_slug
        num = 1
        import uuid

        while Recipe.objects.filter(slug=slug).exclude(id=instance.id).exists():
            slug = f"{base_slug}-{str(uuid.uuid4())[:8]}"

        instance.slug = slug

pre_save.connect(recipe_pre_save, sender=Recipe)

# class Recipe_Tag(models.Model):
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
#     recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

class Ingredient(models.Model):
    UNIT_CHOICES = (
        (0, 'Kilogram'),
        (1, 'Gram'),
        (2, 'Litre'),
        (3, 'Piece'),
    )

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=200, decimal_places=2)
    unit = models.IntegerField(choices=UNIT_CHOICES)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

django_projects/news_project/recipe/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'image', 'author', 'tags']
        exclude = ['author']


    def __init__(self, *args, **kwargs):        
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})
        self.fields['tags'].widget.attrs.update({'class': 'form-control'})


class IngredientCreateForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['title', 'recipe', 'is_active', 'quantity', 'unit']
        exclude = ['recipe']
    
    def __init__(self, *args, **kwargs):
        super(IngredientCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'}) 
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['unit'].widget.attrs.update({'class': 'form-control'})
    

django_projects/news_project/recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Recipe, Ingredient, Tag
from django.contrib.auth.models import User, AbstractBaseUser, Permission
from .forms import RecipeForm, IngredientCreateForm
from django.core.paginator import Paginator

# Create your views here.


def recipe_list(request):
    recipes = Recipe.objects.all()
    query = request.GET.get('q')
    tag = request.GET.get('tag')

    paginator = Paginator(recipes, 1)
    page_number = request.GET.get('page')
    page_qs = paginator.get_page(page_number)

    if query:
        recipes = recipes.filter(author__username__icontains=query)

    if tag:
        recipes = recipes.filter(tags__title__icontains=tag)
    context = {
        'recipes': page_qs,
    }

    return render(request, 'recipe/index.html', context)


def my_recipe(request):
    if not request.user.is_authenticated:
        messages.error(request, "You must be logged in to see your recipe")
        reverse_url = reverse('auth_user:login') + '?next=' + request.path
        return redirect(reverse_url)
    recipes = Recipe.objects.filter(author=request.user)
    print(recipes)
    context = {
        'recipes': recipes,
    }
    return render(request, 'recipe/my_recipe.html', context)
    




def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    ingredients = Ingredient.objects.filter(recipe__author=recipe.author.id)
    is_author = request.user == recipe.author
    print(is_author)
    context = {
        'recipe': recipe,
        'ingredients': ingredients,
        'is_author': is_author
    }
    return render(request, 'recipe/detail.html', context)


def recipe_create(request):
    if not request.user.is_authenticated:
        messages.warning(request, "You must be logged in to create a recipe")
        reverse_url = reverse('auth_user:login') + '?next=' + request.path
        return redirect(reverse_url)
    form = RecipeForm()
    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            form.save_m2m()
            return redirect('recipe:list')
    context = {
        'form': form
    }
    return render(request, 'recipe/create_form.html', context)

def recipe_update(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if not request.user.is_authenticated:
        messages.warning(request, "You must be logged in to update a recipe")
        reverse_url = reverse('auth_user:login') + '?next=' + request.path
        return redirect(reverse_url)
    form = RecipeForm(instance=recipe)
    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author.id = request.user.id
            recipe.save()
            form.save_m2m()
            reverse_url = reverse('recipe:detail', args=[recipe.slug])
            return redirect(reverse_url)
    context = {
        'form': form
    }
    return render(request, 'recipe/update.html', context)


def recipe_delete(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if not request.user.is_authenticated:
        messages.warning(request, "You must be logged in to delete a recipe")
        reverse_url = reverse('auth_user:login') + '?next=' + request.path
        return redirect(reverse_url)
    
    if request.method == "POST":
        recipe.delete()
        messages.error(request, f"'{recipe.title}' successfully deleted")
        return redirect('recipe:list')

    context = {
        'object': recipe
    }

    return render(request, 'recipe/delete_recipe.html', context)



def ingredient_create(request, slug):
    if not request.user.is_authenticated:
        messages.warning(request, "You must be logged in to create an ingredient")
        reverse_url = reverse('auth_user:login') + '?next=' + request.path
        return redirect(reverse_url)
    recipe = get_object_or_404(Recipe, slug=slug)
    form = IngredientCreateForm()
    if request.method == "POST":
        form = IngredientCreateForm(request.POST)
        if form.is_valid():
            ingredient = form.save(commit=False) 
            ingredient.recipe = recipe
            ingredient.save()
            messages.success(request, "Ingredient successfully created")
            reverse_url = reverse('recipe:detail', args=[recipe.slug])
            return redirect(reverse_url)
        
    context = {
        'form': form,
        'recipe': recipe
    }
    return render(request, 'recipe/ingredient_create.html', context)

django_projects/news_project/templates/recipe/create_form.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
<h1>Create Recipe</h1>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/recipe/delete_recipe.html
{% extends 'base.html' %}

{% load static %}

{% block header %}

{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <h2>Are you sure?</h2>
            <p>Are you sure you want to delete the Recipe "{{ object.title }}"? All of the following related items will be deleted:</p>

            <strong>Summary</strong>
            <ul>
                <li>Recipe: {{ object.title }}</li>
            </ul>
            <strong>Objects</strong>
            <ul>
                <li>Recipe quantity : {{ object|length }}</li>
            </ul>
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-info" value="Yes, I'm sure">
                    <a href="{% url 'recipe:detail' object.slug %}" class="btn btn-danger">No, take me back</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/recipe/detail.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
  {% include 'navbar.html' %}
  <h1>Recipe Details</h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ recipe.image.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ recipe.title }}</h5>
              <h6>Author: <em>{{ recipe.author }}</em></h6>
              <p class="card-text">{{ recipe.description }}</p>
              <p class="card-text">
                <small class="text-body-secondary">
                  Last updated {{ recipe.updated_at|timesince }} ago
                </small>
              </p>
                <div class="d-flex gap-2">
                  {% if is_author %}
                    <a href="{% url 'recipe:recipe_update' recipe.slug %}" class="btn btn-info">Edit Recipe</a>
                    <a href="{% url 'recipe:recipe_delete' recipe.slug %}" class="btn btn-danger">Remove Recipe</a>
                    <a href="{% url 'recipe:ingredient_create' recipe.slug %}" class="btn btn-primary">Add Ingredients</a>
                  {% endif %}
                </div>
            </div>
          </div>
        </div>
        <div class="row">
          {% for ingredient in ingredients %}
            <div class="col-sm-4 mb-3 mb-sm-3 my-3">
              <div class="card d-flex">
                <div class="card-body">
                  <h5 class="card-title">{{ ingredient.title }}</h5>
                  <p class="card-text">{{ ingredient.quantity }} {{ ingredient.get_unit_display }}</p>
                  {% if is_author %}
                    <a href="" class="btn btn-primary">Edit Ingredient</a>
                    <a href="" class="btn btn-danger">Remove Ingredient</a>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

django_projects/news_project/templates/recipe/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'navbar.html' %}
<div class="row">
    <h1>Recipes List</h1>
</div>

{% endblock %}

{% block content %}
    <div class="row">
        {% if user.is_authenticated %}
            <a href="{% url 'recipe:recipe_create' %}" class="btn btn-success my-3">Add Recipe</a>
        {% endif %}
        
        {% for recipe in recipes %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.title }}</h5>
                        <h6>Author: <em><a href="?q={{ recipe.author }}">{{ recipe.author }}</a></em></h6>
                        <p class="card-text">{{ recipe.description|slice:" :200" }}...</p>
                        {% for tag in recipe.tags.all %}
                            <mark><a href="?tag={{ tag }}">{{ tag }}</a></mark>
                        {% endfor %}
                        <p class="card-text"><small class="text-body-secondary">Last updated {{ recipe.updated_at|timesince }} ago</small></p>
                        <a href="{% url 'recipe:detail' recipe.slug %}" class="btn btn-primary">About it</a>
                    </div>
                </div>
            </div>
        {% endfor %}


        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              <li class="page-item {% if not recipes.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if recipes.has_previous %}?page={{ recipes.previous_page_number }}{% endif %}">Previous</a>
              </li>
              {% for page_num in recipes.paginator.page_range %}
                <li class="page-item"><a class="page-link {% if recipes.number == page_num %} active {% endif %}" href="?page={{ page_num }}">{{ page_num }}</a></li>
              {% endfor %}
              <li class="page-item {% if not recipes.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if recipes.has_next %}?page={{ recipes.next_page_number }}{% endif %}">Next</a>
              </li>
            </ul>
        </nav>


    </div>
{% endblock %}

django_projects/news_project/templates/recipe/ingredient_create.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
<h1>{{ recipe.title }} || Ingredient</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/recipe/my_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'navbar.html' %}
<div class="row">
    <h1>Recipes List</h1>
</div>

{% endblock %}

{% block content %}
    {% if recipes %}
        <div class="row">
            {% if user.is_authenticated %}
                <a href="{% url 'recipe:recipe_create' %}" class="btn btn-success my-3">Add Recipe</a>
            {% endif %}
            
            {% for recipe in recipes %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <h6>Author: <em><a href="?q={{ recipe.author }}">{{ recipe.author }}</a></em></h6>
                            <p class="card-text">{{ recipe.description|slice:" :200" }}...</p>
                            <p class="card-text"><small class="text-body-secondary">Last updated {{ recipe.updated_at|timesince }} ago</small></p>
                            <a href="{% url 'recipe:detail' recipe.slug %}" class="btn btn-primary">About it</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        {% if user.is_authenticated %}
            <a href="{% url 'recipe:recipe_create' %}" class="btn btn-success my-3">Add Recipe</a>
        {% endif %}
        <div class="row">
            <h1>No recipes found</h1>
        </div>
    {% endif %}
{% endblock %}

django_projects/news_project/templates/recipe/update.html
{% extends 'base.html' %}

{% load static %}   

{% block header %}
<h1>Update Recipe</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}