django_projects/news_project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("auth_user/", include("auth_user.urls", namespace="auth_user")),
    path("recipe/", include("recipe.urls", namespace="recipe"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_projects/news_project/main/urls.py
from django.urls import path
from .views import index, blog, detail, create, create_form, delete, update

app_name = 'main'


urlpatterns = [
    path("", index, name="index"),
    path("article/", blog, name="blogs"),
    path("article/<slug:slug>", detail, name="detail"),
    path("create/", create, name="create"),
    path("create-form/", create_form, name="create_form"),
    path("article/delete/<int:pk>", delete, name="delete"),
    path("article/update/<int:pk>", update, name="update"),
]

django_projects/news_project/templates/article/blogs.html
{% extends 'base.html' %}

{% load static %}


{% block header %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <h1 style="color: #ff5733; font-weight: bold;">Article list</h1>
            <h2 class="text-muted fst-italic fs-5">Article List page</h2>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-8 my-3">
                    <form class="form-control d-flex my-3 gap-2" action="{% url 'main:blogs' %}" method="get">
                        <input type="search" class="form-control" name="q" placeholder="search ...">
                        <button type="submit" class="btn btn-success">submit</button>
                    </form>
                </div>
                <div class="col-4">
                    <span>{{ new.count }} object found</span>
                </div>
            </div>
            {% if new %}
                {% for ne in new %}
                    <div class="col-md-4">
                        <div class="card bg-light border border-secondary hover-effect" style="width: 18rem;">
                            {% if ne.image %}
                                <img src="{{ ne.image.url }}" alt="...">
                            {% else %}
                                <h2 class="text-danger">No image</h2>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ ne.title }}</h5>
                                <p class="card-text">{{ ne.content | slice:":300" }}</p>
                                <a href="{% url 'main:detail' ne.slug %}" class="btn btn-primary">ABOUT IT</a>
                            </div>
                        </div>

                        {#                        <!-- Back to Home button -->#}
                    </div>
                {% endfor %}
            {% else %}
                <h2>No found</h2>
            {% endif %}
            <div>
                <a href="{% url 'main:index' %}" class="back-home">⬅ Back to home page</a>
            </div>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/create-form.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="row">
        <figure>
            <blockquote class="blockquote">
                <p>Create Page</p>
            </blockquote>
            <figcaption class="blockquote-footer">
                <a href="{% url 'main:blogs' %}">home</a> / <span>create-form</span>
            </figcaption>
        </figure>
    </div>

    <div class="row">
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/create.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="row">
        <figure>
            <blockquote class="blockquote">
                <p>Create Page</p>
            </blockquote>
            <figcaption class="blockquote-footer">
                <a href="{% url 'main:blogs' %}">home</a> / <span>create</span>
            </figcaption>
        </figure>
    </div>

    <div class="row">
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleInputTitle" class="form-label">Title</label>
                    <input type="text" class="form-control" name="title" id="exampleInputTitle"
                           aria-describedby="">
                </div>
                <div class="mb-3">
                    <label for="exampleInputContent" class="form-label">Password</label>
                    <input type="text" class="form-control" name="content" id="exampleInputContent">
                </div>
                <div class="mb-3">
                    <input type="file" class="form-image" name="image" id="exampleImage">
                    <label class="form-label" for="exampleImage"></label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/delete.html
{% extends 'base.html' %}

{% load static %}

{% block header %}

{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row">
            <h2>Are you sure?</h2>
            <p>Are you sure you want to delete the new "hi"? All of the following related items will be deleted:</p>

            <strong>Summary</strong>
            <ul>
                <li>Article Title: {{ object.title }}</li>
            </ul>
            <strong>Objects</strong>
            <ul>
                <li>Article content: {{ object.content }}</li>
            </ul>
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-info" value="Yes, I'm sure">
                    <a href="{% url 'main:detail' object.slug %}" class="btn btn-danger">No, take me back</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/detail.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
    {% include 'navbar.html' %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h1>ARTICLE DETAIL PAGE</h1>
            <a href="{% url 'main:blogs' %}">Article</a> / <span>detail</span>
        </div>
        <div class="col-12">
            {% if object.image %}
                <img src="{{ object.image.url }}" alt="">
            {% else %}
                <h2 class="text-danger">No Image</h2>
            {% endif %}
            <hr>
            <h3>{{ object.title }}</h3>
            <p>{{ object.content }}</p>
        </div>
    </div>

    <div class="row">
        <div class="co-md-4">
            <a href="{% url 'main:delete' object.id %}" class="btn btn-danger">Remove Article</a>
            <a href="{% url 'main:update' object.id %}" class="btn btn-info">Update Article</a>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/index.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
    <style>
        body {
            background: url("{% static 'image/news.png' %}") no-repeat center center fixed;
            background-size: cover;
        }
    </style>
        <div class="row">
            <h1>Hello this is NEWS site if you're interested in news then click here |</h1>
            <figure>
                <blockquote class="blockquote">
                    <p>WELCOME TO HOME PAGE</p>
                </blockquote>
                <figcaption class="blockquote-footer">
                    <a href="">home/</a>
                </figcaption>
            </figure>


            <div class="turn">
                <p class="p-news"><a href="{% url 'main:blogs' %}" style="color: #ffffff; text-decoration: none">Turn to News</a></p>
            </div>
        </div>
    </div>
{% endblock %}

django_projects/news_project/templates/article/update.html
{% extends 'base.html' %}

{% load static %}

{% block header %}
    <h1 class="text-info">Update Article</h1>
    <a href="{% url 'main:blogs' %}">article</a> / <span>Update</span>
{% endblock %}

{% block content %}
    <form action="{% url 'main:blogs' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}